import React from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Store, MonitorPlay, Share2, ArrowRight, Play } from 'lucide-react';
import { useAuthModalStore } from '../store/authModalStore';
import { Button } from '../components/ui/button';
import { ThemeToggle } from '../components/ThemeToggle';
import { PlaylistCover } from '../components/PlaylistCover';

const ease = [0.16, 1, 0.3, 1] as const;

const Reveal: React.FC<{ children: React.ReactNode; delay?: number; className?: string }> = ({
  children, delay = 0, className,
}) => (
  <motion.div
    className={className}
    initial={{ opacity: 0, y: 26 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true, margin: '-80px' }}
    transition={{ duration: 0.7, ease, delay }}
  >
    {children}
  </motion.div>
);

const FEATURES = [
  { icon: <Sparkles size={20} />, title: 'AI that gets your taste', body: 'Describe a mood in plain words and Gemini composes a playlist — duplicate-aware, tuned to your library, ready in seconds.' },
  { icon: <Store size={20} />, title: 'One tap for any room', body: 'Cafe, gym, spa, hotel, bar — tap a space and get a playlist built for its exact energy. No prompts, no fiddling.' },
  { icon: <MonitorPlay size={20} />, title: 'Plays right here', body: 'A real player lives in the app — a quiet bottom bar that opens into a full now-playing view with your queue.' },
  { icon: <Share2 size={20} />, title: 'Share a single link', body: 'Send any playlist as a clean, read-only page. Sign in, press play, done.' },
];

export const LandingPage: React.FC = () => {
  const open = useAuthModalStore((s) => s.open);

  return (
    <div className="min-h-screen overflow-x-hidden bg-paper">
      {/* Nav */}
      <header className="sticky top-0 z-40 border-b border-line/70 bg-paper/80 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8">
          <div className="flex items-center gap-2.5">
            <span className="grid h-8 w-8 place-items-center rounded bg-accent font-display text-base font-bold text-accent-contrast">H</span>
            <span className="font-display text-lg font-semibold tracking-tight text-ink">Harmonia</span>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="sm" onClick={() => open('login')}>Sign in</Button>
            <Button variant="accent" size="sm" onClick={() => open('register')}>Get started</Button>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="mx-auto max-w-6xl px-5 pb-20 pt-20 text-center lg:px-8 lg:pt-32">
        <Reveal>
          <span className="inline-flex items-center gap-2 rounded-full border border-line bg-surface px-3.5 py-1.5 text-xs font-medium text-ink-soft">
            <Sparkles size={13} className="text-accent-ink" /> AI-composed music, beautifully organized
          </span>
        </Reveal>
        <Reveal delay={0.06}>
          <h1 className="mx-auto mt-7 max-w-4xl font-display text-5xl font-semibold leading-[1.04] tracking-tight text-ink sm:text-6xl lg:text-7xl">
            Your music,
            <br />
            <span className="text-accent-ink">perfectly composed.</span>
          </h1>
        </Reveal>
        <Reveal delay={0.12}>
          <p className="mx-auto mt-6 max-w-xl text-lg leading-relaxed text-muted">
            Harmonia turns a sentence into the right playlist — generated by AI, tuned to your taste,
            and played without ever leaving the page.
          </p>
        </Reveal>
        <Reveal delay={0.18}>
          <div className="mt-9 flex items-center justify-center gap-3">
            <Button variant="accent" size="lg" onClick={() => open('register')}>
              Start listening <ArrowRight size={16} />
            </Button>
            <Button variant="outline" size="lg" onClick={() => open('login')}>I have an account</Button>
          </div>
        </Reveal>

        {/* Product mock */}
        <Reveal delay={0.24} className="mt-16">
          <div className="mx-auto max-w-3xl overflow-hidden rounded-2xl border border-line bg-surface shadow-[var(--shadow-lg)]">
            <div className="flex items-center gap-1.5 border-b border-line px-4 py-3">
              <span className="h-2.5 w-2.5 rounded-full bg-line-strong" />
              <span className="h-2.5 w-2.5 rounded-full bg-line-strong" />
              <span className="h-2.5 w-2.5 rounded-full bg-line-strong" />
            </div>
            <div className="p-6">
              <div className="mb-4 text-left font-display text-lg font-semibold text-ink">Good evening</div>
              <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                {[
                  ['Midnight Jazz', 'Jazz'], ['Cosmic Drive', 'Electronic'],
                  ['Sunday Coffee', 'Acoustic'], ['Gym Mix', 'Workout'],
                ].map(([n, g], i) => (
                  <PlaylistCover key={n} name={n!} genre={g!} index={i + 1} className="aspect-[4/3] rounded-md" />
                ))}
              </div>
              <div className="mt-5 flex items-center gap-3 rounded-lg border border-line bg-paper-2 px-3 py-2.5">
                <span className="grid h-9 w-9 place-items-center rounded-full bg-accent text-accent-contrast"><Play size={15} className="translate-x-px" /></span>
                <div className="text-left">
                  <div className="text-sm font-medium text-ink">So What</div>
                  <div className="text-xs text-muted">Miles Davis</div>
                </div>
                <div className="ml-auto hidden h-1 w-40 overflow-hidden rounded-full bg-line-strong sm:block">
                  <div className="h-full w-1/3 bg-accent" />
                </div>
              </div>
            </div>
          </div>
        </Reveal>
      </section>

      {/* Features */}
      <section className="border-t border-line bg-surface/40">
        <div className="mx-auto max-w-6xl px-5 py-24 lg:px-8">
          <Reveal>
            <h2 className="max-w-2xl font-display text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
              Everything you need to find the moment’s sound.
            </h2>
          </Reveal>
          <div className="mt-14 grid gap-x-10 gap-y-12 sm:grid-cols-2">
            {FEATURES.map((f, i) => (
              <Reveal key={f.title} delay={(i % 2) * 0.08}>
                <div className="flex gap-4">
                  <span className="grid h-11 w-11 shrink-0 place-items-center rounded-lg border border-line bg-paper text-accent-ink">
                    {f.icon}
                  </span>
                  <div>
                    <h3 className="font-display text-xl font-semibold text-ink">{f.title}</h3>
                    <p className="mt-1.5 text-[0.95rem] leading-relaxed text-muted">{f.body}</p>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* Statement */}
      <section className="mx-auto max-w-5xl px-5 py-28 text-center lg:px-8">
        <Reveal>
          <p className="font-display text-3xl font-medium leading-snug tracking-tight text-ink sm:text-4xl lg:text-[2.75rem]">
            From a single sentence to a finished playlist —
            <span className="text-muted"> Harmonia handles the rest.</span>
          </p>
        </Reveal>
      </section>

      {/* CTA band */}
      <section className="border-t border-line">
        <div className="mx-auto max-w-6xl px-5 py-24 text-center lg:px-8">
          <Reveal>
            <h2 className="font-display text-4xl font-semibold tracking-tight text-ink sm:text-5xl">
              Start composing tonight.
            </h2>
            <p className="mx-auto mt-4 max-w-md text-muted">Free to try. Your first playlist is one sentence away.</p>
            <div className="mt-8">
              <Button variant="accent" size="lg" onClick={() => open('register')}>
                Get started <ArrowRight size={16} />
              </Button>
            </div>
          </Reveal>
        </div>
      </section>

      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-3 px-5 py-8 text-sm text-muted sm:flex-row lg:px-8">
          <div className="flex items-center gap-2">
            <span className="grid h-6 w-6 place-items-center rounded bg-accent font-display text-xs font-bold text-accent-contrast">H</span>
            <span className="font-display font-semibold text-ink">Harmonia</span>
          </div>
          <span>© {new Date().getFullYear()} Harmonia. Composed with care.</span>
        </div>
      </footer>

      <ThemeToggle />
    </div>
  );
};
